In [4]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

In [5]:
import abc
import tensorflow as tf
import numpy as np

import base64
import imageio
import IPython
import matplotlib
import matplotlib.pyplot as plt
import PIL.Image
import pyvirtualdisplay

In [6]:
from tf_agents.environments import py_environment
from tf_agents.environments import tf_environment
from tf_agents.environments import tf_py_environment
from tf_agents.environments import utils
from tf_agents.environments import wrappers
from tf_agents.environments import suite_gym
from tf_agents.environments import suite_mujoco
from tf_agents.trajectories import time_step as ts
from tf_agents.specs import array_spec

In [7]:
# Enable v2 behavior
tf.compat.v1.enable_v2_behavior()
# Set up a virtual display for rendering OpenAI gym environments.
display = pyvirtualdisplay.Display(visible=0, size=(1400, 900)).start()

In [8]:
environment = suite_gym.load('CartPole-v0')
print('action_spec:', environment.action_spec())
print('time_step_spec.observation', environment.time_step_spec().observation)
print('time_step_spec.reward', environment.time_step_spec().reward)
print('time_step_spec.discount', environment.time_step_spec().discount)
print('time_step_spec.step_type', environment.time_step_spec().step_type)


action_spec: BoundedArraySpec(shape=(), dtype=dtype('int64'), name=None, minimum=0, maximum=1)
time_step_spec.observation BoundedArraySpec(shape=(4,), dtype=dtype('float32'), name=None, minimum=[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], maximum=[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38])
time_step_spec.reward ArraySpec(shape=(), dtype=dtype('float32'), name='reward')
time_step_spec.discount BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0)
time_step_spec.step_type ArraySpec(shape=(), dtype=dtype('int32'), name='step_type')


In [9]:
action = 1
time_step = environment.reset()
print(time_step)

TimeStep(step_type=array(0, dtype=int32), reward=array(0., dtype=float32), discount=array(1., dtype=float32), observation=array([-0.03054085,  0.02499142,  0.0277015 ,  0.01631059], dtype=float32))


In [10]:
while not time_step.is_last():
    time_step = environment.step(action)
    print(time_step)

TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([-0.03004102,  0.21970537,  0.02802771, -0.26750508], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([-0.02564692,  0.41441634,  0.02267761, -0.55121773], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([-0.01735859,  0.6092126 ,  0.01165325, -0.83667034], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([-0.00517434,  0.8041734 , -0.00508015, -1.1256658 ], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([ 0.01090913,  0.9993616 , -0.02759347, -1.4199378 ], dtype=float32))
TimeStep(s

In [11]:
env = suite_mujoco.load('HalfCheetah-v2')

In [12]:
print('action_spec:', env.action_spec())
print('time_step_spec.observation', env.time_step_spec().observation)
print('time_step_spec.reward', env.time_step_spec().reward)
print('time_step_spec.discount', env.time_step_spec().discount)
print('time_step_spec.step_type', env.time_step_spec().step_type)

action_spec: BoundedArraySpec(shape=(6,), dtype=dtype('float32'), name=None, minimum=[-1. -1. -1. -1. -1. -1.], maximum=[1. 1. 1. 1. 1. 1.])
time_step_spec.observation BoundedArraySpec(shape=(17,), dtype=dtype('float32'), name=None, minimum=[-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38], maximum=[3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38
 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38
 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38
 3.4028235e+38 3.4028235e+38])
time_step_spec.reward ArraySpec(shape=(), dtype=dtype('float32'), name='reward')
time_step_spec.discount BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0)
time_step_spec.step_type ArraySpec(shape=(), d

In [13]:
tf_env = tf_py_environment.TFPyEnvironment(env)

print(isinstance(tf_env, tf_environment.TFEnvironment))
print("TimeStep Specs:", tf_env.time_step_spec())
print("Action Specs:", tf_env.action_spec())

True
TimeStep Specs: TimeStep(step_type=TensorSpec(shape=(), dtype=tf.int32, name='step_type'), reward=TensorSpec(shape=(), dtype=tf.float32, name='reward'), discount=BoundedTensorSpec(shape=(), dtype=tf.float32, name='discount', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32)), observation=BoundedTensorSpec(shape=(17,), dtype=tf.float32, name=None, minimum=array([-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38], dtype=float32), maximum=array([3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38]

In [14]:
from tf_agents.policies import random_tf_policy

time_step = tf_env.reset()
num_steps = 3
transitions = []
reward = 0
random_policy = random_tf_policy.RandomTFPolicy(action_spec=tf_env.action_spec(),
                                               time_step_spec=tf_env.time_step_spec())

for i in range(num_steps):
    action_step = random_policy.action(time_step)
    action = action_step.action
    next_time_step = tf_env.step(action)
    transitions.append([time_step, action, next_time_step])
    reward += next_time_step.reward
    time_step = next_time_step
    
np_transitions = tf.nest.map_structure(lambda x: x.numpy(), transitions)
print('\n'.join(map(str, np_transitions)))
print('Total reward:', reward.numpy())

[TimeStep(step_type=array([0], dtype=int32), reward=array([0.], dtype=float32), discount=array([1.], dtype=float32), observation=array([[ 0.04096488, -0.04456011,  0.03539135,  0.00959783,  0.0405442 ,
        -0.0952404 ,  0.05411316,  0.06147752,  0.12355213, -0.21735004,
         0.11308104,  0.07886522, -0.23104899, -0.05057145, -0.06557063,
        -0.07195956,  0.05116129]], dtype=float32)), array([[ 0.12916636, -0.4701333 , -0.1957438 , -0.2429452 ,  0.41729975,
        -0.45938134]], dtype=float32), TimeStep(step_type=array([1], dtype=int32), reward=array([0.03592229], dtype=float32), discount=array([1.], dtype=float32), observation=array([[ 0.02386188, -0.02302459,  0.08942886, -0.18066144, -0.06220927,
        -0.15312383,  0.17080186, -0.10673446,  0.08011492, -0.5249965 ,
         0.48879454,  0.95780903, -4.3135786 , -2.4086382 , -1.3559316 ,
         2.829659  , -4.6082335 ]], dtype=float32))]
[TimeStep(step_type=array([1], dtype=int32), reward=array([0.03592229], dtype=f

In [15]:
nested_array = tf.nest.flatten(tf.random.uniform(shape=[10, 299, 299, 3]).numpy());
array = tf.nest.flatten(nested_array)
len(array)
arr = tf.random.uniform(shape=[2,1])
print(arr)
print(tf.math.reduce_max(arr))
print(tf.math.argmax(arr, axis = 1))

tf.Tensor(
[[0.28794646]
 [0.711594  ]], shape=(2, 1), dtype=float32)
tf.Tensor(0.711594, shape=(), dtype=float32)
tf.Tensor([0 0], shape=(2,), dtype=int64)


In [16]:
input_size = env.action_spec().shape[0] + env.time_step_spec().observation.shape[0]
print(input_size)
output_size = env.time_step_spec().observation.shape[0]
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(input_size, )),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(output_size)
])


optimizer = tf.keras.optimizers.Adam()
loss_history = []

for time_step, action, next_time_step in transitions:
    state_diff = next_time_step.observation - time_step.observation
    
    with tf.GradientTape() as tape:
        print('Observation', time_step.observation)
        print('Action', action)
        pred_state_diff = model(tf.concat([time_step.observation, action], 1), training=True)   
        loss_value = tf.losses.mean_squared_error(state_diff, pred_state_diff)
    
    loss_history.append(loss_value.numpy())
    grads = tape.gradient(loss_value, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
        

print(loss_history)

    

23
Observation tf.Tensor(
[[ 0.04096488 -0.04456011  0.03539135  0.00959783  0.0405442  -0.0952404
   0.05411316  0.06147752  0.12355213 -0.21735004  0.11308104  0.07886522
  -0.23104899 -0.05057145 -0.06557063 -0.07195956  0.05116129]], shape=(1, 17), dtype=float32)
Action tf.Tensor([[ 0.12916636 -0.4701333  -0.1957438  -0.2429452   0.41729975 -0.45938134]], shape=(1, 6), dtype=float32)
Observation tf.Tensor(
[[ 0.02386188 -0.02302459  0.08942886 -0.18066144 -0.06220927 -0.15312383
   0.17080186 -0.10673446  0.08011492 -0.5249965   0.48879454  0.95780903
  -4.3135786  -2.4086382  -1.3559316   2.829659   -4.6082335 ]], shape=(1, 17), dtype=float32)
Action tf.Tensor([[-0.08561516 -0.4688561  -0.9777341  -0.9109969   0.04478097 -0.3444512 ]], shape=(1, 6), dtype=float32)
Observation tf.Tensor(
[[-2.4857866e-02  1.9296164e-02  5.4148696e-03 -2.8643462e-01
  -4.2511880e-01 -4.0445280e-01  2.0377558e-01 -2.3186734e-01
  -5.5300891e-01 -1.2891542e+00  1.0162114e+00 -2.9272718e+00
  -8.361160

In [17]:
from tf_agents.policies import py_policy
from tf_agents.policies import tf_policy
from tf_agents.specs import array_spec
from tf_agents.trajectories import policy_step
from tf_agents.trajectories import time_step as ts
from tf_agents.utils import nest_utils


class ModelBasedPolicy(py_policy.Base):
    
    def __init__(self, 
                 time_step_spec, 
                 action_spec, 
                 dynamics_model_network,
                 num_random_action_selection=4096,
                 horizon=15):
        
        if time_step_spec is None:
            time_step_spec = ts.time_step_spec()
        self._dynamics_model_network = dynamics_model_network
        self._num_random_action_selection=num_random_action_selection
        self._horizon = horizon
        
        super(ModelBasedPolicy, self).__init__(
            time_step_spec=time_step_spec, action_spec=action_spec)
        
    def _action(self, time_step, policy_state):
        
        random_actions = array_spec.sample_spec_nest(
            self._action_spec, np.random.RandomState(), outer_dims=[self._num_random_action_selection, self._horizon])
        start_state = tf.tile(time_step.observation, [self._num_random_action_selection, 1])
        cost = tf.zeros(shape=[self._num_random_action_selection, 1])
        curr_state = start_state
        for h in range(self._horizon):
            next_state = curr_state + self._dynamics_model_network(tf.concat([curr_state, random_actions[:, h, :]], 1))
            cost += self._cost_fn(curr_state, tf.constant(random_actions[:, h, :]), next_state)
            curr_state = next_state
           
        min_cost_index = tf.math.argmin(cost, axis=1)[0]
        return policy_step.PolicyStep(random_actions[min_cost_index, 0, :], policy_state)
    
    def _cost_fn(self, states, actions, next_states):
        is_tf = tf.is_tensor(states)
        is_single_state = (len(states.get_shape()) == 1) if is_tf else (len(states.shape) == 1)

        if is_single_state:
            states = states[None, ...]
            actions = actions[None, ...]
            next_states = next_states[None, ...]

        scores = tf.zeros(actions.get_shape()[0]) if is_tf else np.zeros(actions.shape[0])

        heading_penalty_factor = 10

        # dont move front shin back so far that you tilt forward
        front_leg = states[:, 6]
        my_range = 0.2
        if is_tf:
            scores += tf.cast(front_leg >= my_range, tf.float32) * heading_penalty_factor
        else:
            scores += (front_leg >= my_range) * heading_penalty_factor

        front_shin = states[:, 7]
        my_range = 0
        if is_tf:
            scores += tf.cast(front_shin >= my_range, tf.float32) * heading_penalty_factor
        else:
            scores += (front_shin >= my_range) * heading_penalty_factor

        front_foot = states[:, 8]
        my_range = 0
        if is_tf:
            scores += tf.cast(front_foot >= my_range, tf.float32) * heading_penalty_factor
        else:
            scores += (front_foot >= my_range) * heading_penalty_factor

        scores -= (next_states[:, 16] - states[:, 16]) / 0.01

        if is_single_state:
            scores = scores[0]

        return scores



In [18]:
my_policy = ModelBasedPolicy(env.time_step_spec(), env.action_spec(), model)
time_step = tf_env.reset()
my_policy.action(time_step)

PolicyStep(action=array([ 0.12087511,  0.8673162 ,  0.6929906 , -0.83383524,  0.84574324,
        0.8653695 ], dtype=float32), state=(), info=())

In [33]:
from tf_agents.agents import tf_agent
from tf_agents.policies import greedy_policy
from tf_agents.policies import random_py_policy
from tf_agents.policies import random_tf_policy

from enum import Enum

class CollectionMode(Enum):
    on_policy=0
    off_policy=1

class ModelBasedAgent(tf_agent.TFAgent):
    
    def __init__(self,
                 time_step_spec,
                 action_spec,
                 dynamics_model_network,
                 optimizer,
                 debug_summaries=False,
                 summarize_grads_and_vars=False,
                 entropy_regularization=None,
                 train_step_counter=None,
                 name=None):
        tf.Module.__init__(self, name=name)
        self._dynamics_model_network = dynamics_model_network    
        collect_policy = random_py_policy.RandomPyPolicy(
                    time_step_spec=time_step_spec,
                    action_spec=action_spec)
        policy = greedy_policy.GreedyPolicy(collect_policy)

        super(ModelBasedAgent, self).__init__(
            time_step_spec,
            action_spec,
            policy,
            collect_policy,
            train_sequence_length=None,
            debug_summaries=debug_summaries,
            summarize_grads_and_vars=summarize_grads_and_vars,
            train_step_counter=train_step_counter)
        
    
    def set_collection_policy(self, collection_mode):
                # Type checking
        if not isinstance(collection_mode, CollectionMode):
            raise TypeError('collection_mode must be an instance of CollectionMode Enum')
        if collection_mode is CollectionMode.on_policy:
                self._collect_policy = ModelBasedPolicy(
                    time_step_spec=super().time_step_spec,
                    action_spec=super().action_spec,
                    dynamics_model_network=self._dynamics_model_network)
        else:
                
                self._collect_policy = random_py_policy.RandomPyPolicy(
                    time_step_spec=super().time_step_spec(),
                    action_spec=super().action_spec())
                
    def _train(self, experience, weights=None):
        state_diff = experience.next_time_step.observation - experience.time_step.observation
        
        with tf.GradientTape() as tape:
            pred_state_diff = self._dynamics_model_network(tf.concat([experience.time_step.observation, experience.action], 1), training=True)   
            loss_value = tf.losses.mean_squared_error(state_diff, pred_state_diff)
            grads = tape.gradient(loss_value, self._dynamics_model_network.trainable_variables)
            optimizer.apply_gradients(zip(grads, self._dynamics_model_network.trainable_variables))


In [34]:
env = suite_mujoco.load('HalfCheetah-v2')
tf_env = tf_py_environment.TFPyEnvironment(env)

input_size = env.action_spec().shape[0] + env.time_step_spec().observation.shape[0]
output_size = env.time_step_spec().observation.shape[0]
dynamics_model_network = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(input_size, )),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(output_size)
])

learning_rate = 1e-3  
optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)

train_step_counter = tf.compat.v2.Variable(0)

tf_agent = ModelBasedAgent(
    env.time_step_spec(),
    env.action_spec(),
    dynamics_model_network=dynamics_model_network,
    optimizer=optimizer,
    train_step_counter=train_step_counter)
tf_agent.initialize()


In [ ]:
data_spec =  (env.time_step_spec(), env.action_spec(), env.time_step_spec())

batch_size = 1
max_length = 1000

replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec,
    batch_size=batch_size,
    max_length=max_length)