In [126]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

In [127]:
import abc
import tensorflow as tf
import numpy as np

import base64
import imageio
import IPython
import matplotlib
import matplotlib.pyplot as plt
import PIL.Image
import pyvirtualdisplay

In [128]:
from tf_agents.environments import py_environment
from tf_agents.environments import tf_environment
from tf_agents.environments import tf_py_environment
from tf_agents.environments import utils
from tf_agents.environments import wrappers
from tf_agents.environments import suite_gym
from tf_agents.environments import suite_mujoco
from tf_agents.trajectories import time_step as ts
from tf_agents.specs import array_spec

In [129]:
# Enable v2 behavior
tf.compat.v1.enable_v2_behavior()
# Set up a virtual display for rendering OpenAI gym environments.
display = pyvirtualdisplay.Display(visible=0, size=(1400, 900)).start()

In [130]:
environment = suite_gym.load('CartPole-v0')
print('action_spec:', environment.action_spec())
print('time_step_spec.observation', environment.time_step_spec().observation)
print('time_step_spec.reward', environment.time_step_spec().reward)
print('time_step_spec.discount', environment.time_step_spec().discount)
print('time_step_spec.step_type', environment.time_step_spec().step_type)


action_spec: BoundedArraySpec(shape=(), dtype=dtype('int64'), name=None, minimum=0, maximum=1)
time_step_spec.observation BoundedArraySpec(shape=(4,), dtype=dtype('float32'), name=None, minimum=[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], maximum=[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38])
time_step_spec.reward ArraySpec(shape=(), dtype=dtype('float32'), name='reward')
time_step_spec.discount BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0)
time_step_spec.step_type ArraySpec(shape=(), dtype=dtype('int32'), name='step_type')


In [131]:
action = 1
time_step = environment.reset()
print(time_step)

TimeStep(step_type=array(0, dtype=int32), reward=array(0., dtype=float32), discount=array(1., dtype=float32), observation=array([-0.04454876,  0.04927505,  0.04358195, -0.00200671], dtype=float32))


In [132]:
while not time_step.is_last():
    time_step = environment.step(action)
    print(time_step)

TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([-0.04356326,  0.24374576,  0.04354182, -0.28062674], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([-0.03868835,  0.4382204 ,  0.03792928, -0.559265  ], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([-0.02992394,  0.63279   ,  0.02674398, -0.83976096], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([-0.01726814,  0.8275368 ,  0.00994876, -1.123915  ], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([-7.1739918e-04,  1.0225270e+00, -1.2529540e-02, -1.4134607e+00],
      dtype=fl

In [133]:
env = suite_mujoco.load('HalfCheetah-v2')

In [134]:
print('action_spec:', env.action_spec())
print('time_step_spec.observation', env.time_step_spec().observation)
print('time_step_spec.reward', env.time_step_spec().reward)
print('time_step_spec.discount', env.time_step_spec().discount)
print('time_step_spec.step_type', env.time_step_spec().step_type)

action_spec: BoundedArraySpec(shape=(6,), dtype=dtype('float32'), name=None, minimum=[-1. -1. -1. -1. -1. -1.], maximum=[1. 1. 1. 1. 1. 1.])
time_step_spec.observation BoundedArraySpec(shape=(17,), dtype=dtype('float32'), name=None, minimum=[-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38], maximum=[3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38
 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38
 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38
 3.4028235e+38 3.4028235e+38])
time_step_spec.reward ArraySpec(shape=(), dtype=dtype('float32'), name='reward')
time_step_spec.discount BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0)
time_step_spec.step_type ArraySpec(shape=(), d

In [135]:
tf_env = tf_py_environment.TFPyEnvironment(env)

print(isinstance(tf_env, tf_environment.TFEnvironment))
print("TimeStep Specs:", tf_env.time_step_spec())
print("Action Specs:", tf_env.action_spec())

True
TimeStep Specs: TimeStep(step_type=TensorSpec(shape=(), dtype=tf.int32, name='step_type'), reward=TensorSpec(shape=(), dtype=tf.float32, name='reward'), discount=BoundedTensorSpec(shape=(), dtype=tf.float32, name='discount', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32)), observation=BoundedTensorSpec(shape=(17,), dtype=tf.float32, name=None, minimum=array([-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38], dtype=float32), maximum=array([3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38]

In [136]:
from tf_agents.policies import random_tf_policy

time_step = tf_env.reset()
num_steps = 3
transitions = []
reward = 0
random_policy = random_tf_policy.RandomTFPolicy(action_spec=tf_env.action_spec(),
                                               time_step_spec=tf_env.time_step_spec())

for i in range(num_steps):
    action_step = random_policy.action(time_step)
    action = action_step.action
    next_time_step = tf_env.step(action)
    transitions.append([time_step, action, next_time_step])
    reward += next_time_step.reward
    time_step = next_time_step
    
np_transitions = tf.nest.map_structure(lambda x: x.numpy(), transitions)
print('\n'.join(map(str, np_transitions)))
print('Total reward:', reward.numpy())

[TimeStep(step_type=array([0], dtype=int32), reward=array([0.], dtype=float32), discount=array([1.], dtype=float32), observation=array([[-9.1067500e-02, -6.6572793e-02, -4.7095217e-02,  6.9585061e-05,
         4.6733588e-02, -2.0074748e-02, -3.2299198e-02, -1.6512033e-03,
         8.6873144e-02,  1.4975145e-01, -1.0232244e-01,  9.0327315e-02,
        -2.3088583e-01,  1.4822657e-01,  2.7659308e-02, -3.0178087e-02,
         1.9371119e-01]], dtype=float32)), array([[ 0.15088725,  0.14196634,  0.9563999 , -0.706512  , -0.9811747 ,
        -0.30316854]], dtype=float32), TimeStep(step_type=array([1], dtype=int32), reward=array([-0.18825586], dtype=float32), discount=array([1.], dtype=float32), observation=array([[-0.06946053,  0.01491265, -0.09753682,  0.03920974,  0.22235511,
        -0.21333966, -0.25523356, -0.03001392,  0.09362458,  0.3178691 ,
         2.037819  ,  0.07891111, -0.48062405,  7.041334  , -5.7361326 ,
        -6.0308275 , -1.15453   ]], dtype=float32))]
[TimeStep(step_type

In [137]:
nested_array = tf.nest.flatten(tf.random.uniform(shape=[10, 299, 299, 3]).numpy());
array = tf.nest.flatten(nested_array)
len(array)
arr = tf.random.uniform(shape=[2,1])
print(arr)
print(tf.math.reduce_max(arr))
print(tf.math.argmax(arr, axis = 1))

tf.Tensor(
[[0.9469503]
 [0.6618465]], shape=(2, 1), dtype=float32)
tf.Tensor(0.9469503, shape=(), dtype=float32)
tf.Tensor([0 0], shape=(2,), dtype=int64)


In [138]:
input_size = tf_env.action_spec().shape[0] + tf_env.time_step_spec().observation.shape[0]
print(input_size)
output_size = env.time_step_spec().observation.shape[0]
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(input_size, )),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(output_size)
])


optimizer = tf.keras.optimizers.Adam()
loss_history = []

for time_step, action, next_time_step in transitions:
    state_diff = next_time_step.observation - time_step.observation
    
    with tf.GradientTape() as tape:
        print('Observation', time_step.observation)
        print('Action', action)
        pred_state_diff = model(tf.concat([time_step.observation, action], 1), training=True)   
        loss_value = tf.losses.mean_squared_error(state_diff, pred_state_diff)
    
    loss_history.append(loss_value.numpy())
    grads = tape.gradient(loss_value, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
        

print(loss_history)

    

23
Observation tf.Tensor(
[[-9.1067500e-02 -6.6572793e-02 -4.7095217e-02  6.9585061e-05
   4.6733588e-02 -2.0074748e-02 -3.2299198e-02 -1.6512033e-03
   8.6873144e-02  1.4975145e-01 -1.0232244e-01  9.0327315e-02
  -2.3088583e-01  1.4822657e-01  2.7659308e-02 -3.0178087e-02
   1.9371119e-01]], shape=(1, 17), dtype=float32)
Action tf.Tensor([[ 0.15088725  0.14196634  0.9563999  -0.706512   -0.9811747  -0.30316854]], shape=(1, 6), dtype=float32)
Observation tf.Tensor(
[[-0.06946053  0.01491265 -0.09753682  0.03920974  0.22235511 -0.21333966
  -0.25523356 -0.03001392  0.09362458  0.3178691   2.037819    0.07891111
  -0.48062405  7.041334   -5.7361326  -6.0308275  -1.15453   ]], shape=(1, 17), dtype=float32)
Action tf.Tensor([[-0.14627552  0.8115866   0.68825173 -0.28245163 -0.31778455  0.12398553]], shape=(1, 6), dtype=float32)
Observation tf.Tensor(
[[-0.08018537  0.05515653 -0.09212859  0.31302798  0.42751178 -0.3869524
  -0.35476658 -0.03968809  0.39871377 -0.44545272  0.23439011  1.013

In [144]:
from tf_agents.policies import py_policy
from tf_agents.policies import tf_policy
from tf_agents.specs import array_spec
from tf_agents.specs import tensor_spec
from tf_agents.trajectories import policy_step
from tf_agents.trajectories import time_step as ts
from tf_agents.utils import nest_utils


class ModelBasedPolicy(tf_policy.Base):
    
    def __init__(self, 
                 time_step_spec, 
                 action_spec, 
                 dynamics_model_network,
                 num_random_action_selection=4096,
                 horizon=15):
        
        if time_step_spec is None:
            time_step_spec = ts.time_step_spec()
        self._dynamics_model_network = dynamics_model_network
        self._num_random_action_selection=num_random_action_selection
        self._horizon = horizon
        
        super(ModelBasedPolicy, self).__init__(
            time_step_spec=time_step_spec, action_spec=action_spec)
        
    def _action(self, time_step, policy_state, seed):
        
        random_actions = tensor_spec.sample_spec_nest(
            self._action_spec, seed, outer_dims=[self._num_random_action_selection, self._horizon])
        start_state = tf.tile(time_step.observation, [self._num_random_action_selection, 1])
        cost = tf.zeros(shape=[self._num_random_action_selection, 1])
        curr_state = start_state
        for h in range(self._horizon):
            next_state = curr_state + self._dynamics_model_network(tf.concat([curr_state, random_actions[:, h, :]], 1))
            cost += self._cost_fn(curr_state, tf.constant(random_actions[:, h, :]), next_state)
            curr_state = next_state
           
        min_cost_index = tf.math.argmin(cost, axis=1)[0]
        return policy_step.PolicyStep(random_actions[min_cost_index, 0, :], policy_state)
    
    def _cost_fn(self, states, actions, next_states):
        is_tf = tf.is_tensor(states)
        is_single_state = (len(states.get_shape()) == 1) if is_tf else (len(states.shape) == 1)

        if is_single_state:
            states = states[None, ...]
            actions = actions[None, ...]
            next_states = next_states[None, ...]

        scores = tf.zeros(actions.get_shape()[0]) if is_tf else np.zeros(actions.shape[0])

        heading_penalty_factor = 10

        # dont move front shin back so far that you tilt forward
        front_leg = states[:, 6]
        my_range = 0.2
        if is_tf:
            scores += tf.cast(front_leg >= my_range, tf.float32) * heading_penalty_factor
        else:
            scores += (front_leg >= my_range) * heading_penalty_factor

        front_shin = states[:, 7]
        my_range = 0
        if is_tf:
            scores += tf.cast(front_shin >= my_range, tf.float32) * heading_penalty_factor
        else:
            scores += (front_shin >= my_range) * heading_penalty_factor

        front_foot = states[:, 8]
        my_range = 0
        if is_tf:
            scores += tf.cast(front_foot >= my_range, tf.float32) * heading_penalty_factor
        else:
            scores += (front_foot >= my_range) * heading_penalty_factor

        scores -= (next_states[:, 16] - states[:, 16]) / 0.01

        if is_single_state:
            scores = scores[0]

        return scores



In [145]:
from tf_agents.policies import tf_py_policy
from tf_agents.policies import py_tf_policy

my_policy = ModelBasedPolicy(tf_env.time_step_spec(), tf_env.action_spec(), model)
time_step = tf_env.reset()
my_policy.action(time_step)

PolicyStep(action=<tf.Tensor: id=1286687, shape=(6,), dtype=float32, numpy=
array([ 0.88684106, -0.9599197 , -0.8087647 ,  0.93643665,  0.41107225,
       -0.84757185], dtype=float32)>, state=(), info=())

In [181]:
from tf_agents.agents import tf_agent
from tf_agents.policies import greedy_policy
from tf_agents.policies import random_py_policy
from tf_agents.policies import random_tf_policy

from tf_agents.replay_buffers import tf_uniform_replay_buffer
from tf_agents.replay_buffers import py_uniform_replay_buffer
from tf_agents.trajectories import trajectory

from enum import Enum

class CollectionMode(Enum):
    on_policy=0
    off_policy=1

class ModelBasedAgent(tf_agent.TFAgent):
    
    def __init__(self,
                 time_step_spec,
                 action_spec,
                 dynamics_model_network,
                 optimizer,
                 debug_summaries=False,
                 summarize_grads_and_vars=False,
                 entropy_regularization=None,
                 train_step_counter=None,
                 name=None):
        tf.Module.__init__(self, name=name)
        self._dynamics_model_network = dynamics_model_network  
        
        policy = ModelBasedPolicy(
                    time_step_spec=time_step_spec,
                    action_spec=action_spec,
                    dynamics_model_network=self._dynamics_model_network)
        
        collect_policy = policy

        super(ModelBasedAgent, self).__init__(
            time_step_spec,
            action_spec,
            policy,
            collect_policy,
            train_sequence_length=2,
            debug_summaries=debug_summaries,
            summarize_grads_and_vars=summarize_grads_and_vars,
            train_step_counter=train_step_counter)
        
    def _experience_to_transitions(self, experience):
        transitions = trajectory.to_transition(experience)
        time_steps, policy_steps, next_time_steps = transitions
        actions = policy_steps.action
        
        return time_steps, actions, next_time_steps
                
    def _train(self, experience, weights=None):
        time_steps, actions, next_time_steps = self._experience_to_transitions(experience)
        state_diff = next_time_steps.observation - time_steps.observation
        
        with tf.GradientTape() as tape:
            pred_state_diff = self._dynamics_model_network(tf.concat([time_steps.observation, actions], 2), training=True)   
            loss_value = tf.losses.mean_squared_error(state_diff, pred_state_diff)
            grads = tape.gradient(loss_value, self._dynamics_model_network.trainable_variables)
            optimizer.apply_gradients(zip(grads, self._dynamics_model_network.trainable_variables))
            
        return tf.nest.map_structure(tf.identity, tf_agent.LossInfo(loss_value, ())


In [182]:
env = suite_mujoco.load('HalfCheetah-v2')
tf_env = tf_py_environment.TFPyEnvironment(env)

input_size = env.action_spec().shape[0] + env.time_step_spec().observation.shape[0]
output_size = env.time_step_spec().observation.shape[0]
dynamics_model_network = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(input_size, )),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(output_size)
])

learning_rate = 1e-3  
optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)

train_step_counter = tf.compat.v2.Variable(0)

tf_agent = ModelBasedAgent(
    tf_env.time_step_spec(),
    tf_env.action_spec(),
    dynamics_model_network=dynamics_model_network,
    optimizer=optimizer,
    train_step_counter=train_step_counter)
tf_agent.initialize()

In [183]:
replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec=tf_agent.collect_data_spec,
    batch_size=tf_env.batch_size,
    max_length=100000)


initial_collect_policy = random_tf_policy.RandomTFPolicy(
                    tf_env.time_step_spec(),
                    tf_env.action_spec())

In [184]:
from tf_agents.metrics import tf_metrics
from tf_agents.drivers import dynamic_episode_driver
from tf_agents.drivers import dynamic_step_driver

num_rollouts = 1
num_episodes = tf_metrics.NumberOfEpisodes()
env_steps = tf_metrics.EnvironmentSteps()

observers = [num_episodes, env_steps, replay_buffer.add_batch]
collect_driver = dynamic_episode_driver.DynamicEpisodeDriver(
    tf_env, initial_collect_policy, observers, num_episodes=num_rollouts)

# Initial driver.run will reset the environment and initialize the policy.
final_time_step, policy_state = collect_driver.run()

print('final_time_step', final_time_step)
print('Number of Steps: ', env_steps.result().numpy())
print('Number of Episodes: ', num_episodes.result().numpy())

final_time_step TimeStep(step_type=<tf.Tensor: id=3532237, shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>, reward=<tf.Tensor: id=3532238, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>, discount=<tf.Tensor: id=3532239, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>, observation=<tf.Tensor: id=3532240, shape=(1, 17), dtype=float32, numpy=
array([[ 3.2056827e-02,  2.9118804e-05, -7.2078496e-02, -5.7843365e-02,
         9.9020109e-02, -9.7286545e-02,  2.1951772e-02,  5.6241442e-02,
         1.3744840e-01,  1.6716242e-01, -1.8244857e-01,  2.3494018e-02,
        -3.2553342e-03,  9.0839252e-02,  5.2028815e-03,  1.4341048e-02,
         6.1431406e-03]], dtype=float32)>)
Number of Steps:  1000
Number of Episodes:  1


In [ ]:
print(replay_buffer.gather_all().observation.shape)
print(replay_buffer.get_next(num_steps=2)[0].observation.shape)

In [185]:
time_step = None
policy_state = initial_collect_policy.get_initial_state(tf_env.batch_size)

dataset = replay_buffer.as_dataset(
    sample_batch_size=64,
    num_steps=2)

iterator = iter(dataset)

num_iterations = 50

for _ in range(1):
    experience, _ = next(iterator)
    loss_info = tf_agent.train(experience)
    print(loss_info)

    

AttributeError: 'ModelBasedAgent' object has no attribute 'LossInfo'