In [330]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

In [331]:
import abc
import tensorflow as tf
import numpy as np

import base64
import imageio
import IPython
import matplotlib
import matplotlib.pyplot as plt
import PIL.Image
import pyvirtualdisplay

In [332]:
from tf_agents.environments import py_environment
from tf_agents.environments import tf_environment
from tf_agents.environments import tf_py_environment
from tf_agents.environments import utils
from tf_agents.environments import wrappers
from tf_agents.environments import suite_gym
from tf_agents.environments import suite_mujoco
from tf_agents.trajectories import time_step as ts
from tf_agents.specs import array_spec

In [333]:
# Enable v2 behavior
tf.compat.v1.enable_v2_behavior()
# Set up a virtual display for rendering OpenAI gym environments.
display = pyvirtualdisplay.Display(visible=0, size=(1400, 900)).start()

In [334]:
environment = suite_gym.load('CartPole-v0')
print('action_spec:', environment.action_spec())
print('time_step_spec.observation', environment.time_step_spec().observation)
print('time_step_spec.reward', environment.time_step_spec().reward)
print('time_step_spec.discount', environment.time_step_spec().discount)
print('time_step_spec.step_type', environment.time_step_spec().step_type)


action_spec: BoundedArraySpec(shape=(), dtype=dtype('int64'), name=None, minimum=0, maximum=1)
time_step_spec.observation BoundedArraySpec(shape=(4,), dtype=dtype('float32'), name=None, minimum=[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], maximum=[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38])
time_step_spec.reward ArraySpec(shape=(), dtype=dtype('float32'), name='reward')
time_step_spec.discount BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0)
time_step_spec.step_type ArraySpec(shape=(), dtype=dtype('int32'), name='step_type')


In [335]:
action = 1
time_step = environment.reset()
print(time_step)

TimeStep(step_type=array(0, dtype=int32), reward=array(0., dtype=float32), discount=array(1., dtype=float32), observation=array([ 0.01095514, -0.01147377,  0.01208805, -0.00147436], dtype=float32))


In [336]:
while not time_step.is_last():
    time_step = environment.step(action)
    print(time_step)

TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([ 0.01072567,  0.18347275,  0.01205856, -0.290319  ], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([ 0.01439512,  0.3784207 ,  0.00625218, -0.5791745 ], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([ 0.02196353,  0.5734545 , -0.00533131, -0.86988133], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([ 0.03343263,  0.76864856, -0.02272893, -1.1642357 ], dtype=float32))
TimeStep(step_type=array(1, dtype=int32), reward=array(1., dtype=float32), discount=array(1., dtype=float32), observation=array([ 0.04880559,  0.96405894, -0.04601365, -1.4639572 ], dtype=float32))
TimeStep(s

In [337]:
env = suite_mujoco.load('HalfCheetah-v2')

In [338]:
print('action_spec:', env.action_spec())
print('time_step_spec.observation', env.time_step_spec().observation)
print('time_step_spec.reward', env.time_step_spec().reward)
print('time_step_spec.discount', env.time_step_spec().discount)
print('time_step_spec.step_type', env.time_step_spec().step_type)

action_spec: BoundedArraySpec(shape=(6,), dtype=dtype('float32'), name=None, minimum=[-1. -1. -1. -1. -1. -1.], maximum=[1. 1. 1. 1. 1. 1.])
time_step_spec.observation BoundedArraySpec(shape=(17,), dtype=dtype('float32'), name=None, minimum=[-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38 -3.4028235e+38
 -3.4028235e+38], maximum=[3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38
 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38
 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38
 3.4028235e+38 3.4028235e+38])
time_step_spec.reward ArraySpec(shape=(), dtype=dtype('float32'), name='reward')
time_step_spec.discount BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0)
time_step_spec.step_type ArraySpec(shape=(), d

In [339]:
tf_env = tf_py_environment.TFPyEnvironment(env)

print(isinstance(tf_env, tf_environment.TFEnvironment))
print("TimeStep Specs:", tf_env.time_step_spec())
print("Action Specs:", tf_env.action_spec())

True
TimeStep Specs: TimeStep(step_type=TensorSpec(shape=(), dtype=tf.int32, name='step_type'), reward=TensorSpec(shape=(), dtype=tf.float32, name='reward'), discount=BoundedTensorSpec(shape=(), dtype=tf.float32, name='discount', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32)), observation=BoundedTensorSpec(shape=(17,), dtype=tf.float32, name=None, minimum=array([-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38], dtype=float32), maximum=array([3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
       3.4028235e+38]

In [340]:
from tf_agents.policies import random_tf_policy

time_step = tf_env.reset()
num_steps = 3
transitions = []
reward = 0
random_policy = random_tf_policy.RandomTFPolicy(action_spec=tf_env.action_spec(),
                                               time_step_spec=tf_env.time_step_spec())

for i in range(num_steps):
    action_step = random_policy.action(time_step)
    action = action_step.action
    next_time_step = tf_env.step(action)
    transitions.append([time_step, action, next_time_step])
    reward += next_time_step.reward
    time_step = next_time_step
    
np_transitions = tf.nest.map_structure(lambda x: x.numpy(), transitions)
print('\n'.join(map(str, np_transitions)))
print('Total reward:', reward.numpy())

[TimeStep(step_type=array([0], dtype=int32), reward=array([0.], dtype=float32), discount=array([1.], dtype=float32), observation=array([[-0.03723973,  0.08865002, -0.03914903, -0.08089941,  0.00092869,
         0.08897705, -0.09163773,  0.04546549,  0.01857329,  0.09931803,
        -0.03349365,  0.01707685, -0.04606488, -0.08050357, -0.110457  ,
        -0.1112295 , -0.12238962]], dtype=float32)), array([[ 0.7629349 , -0.65688777,  0.8418231 , -0.6948137 ,  0.36854053,
        -0.53573465]], dtype=float32), TimeStep(step_type=array([1], dtype=int32), reward=array([-0.17309183], dtype=float32), discount=array([1.], dtype=float32), observation=array([[-0.02790391,  0.09771752,  0.18591745, -0.37610778,  0.3022899 ,
        -0.20966941,  0.21534038, -0.11377001,  0.08316024, -0.03846378,
         0.12309174,  5.5717487 , -6.138163  ,  7.2941446 , -7.6280513 ,
         7.1246557 , -4.271552  ]], dtype=float32))]
[TimeStep(step_type=array([1], dtype=int32), reward=array([-0.17309183], dtype

In [341]:
nested_array = tf.nest.flatten(tf.random.uniform(shape=[10, 299, 299, 3]).numpy());
array = tf.nest.flatten(nested_array)
len(array)
arr = tf.random.uniform(shape=[2,1])
print(arr)
print(tf.math.reduce_max(arr))
print(tf.math.argmax(arr, axis = 1))

tf.Tensor(
[[0.6215117]
 [0.1370089]], shape=(2, 1), dtype=float32)
tf.Tensor(0.6215117, shape=(), dtype=float32)
tf.Tensor([0 0], shape=(2,), dtype=int64)


In [342]:
input_size = tf_env.action_spec().shape[0] + tf_env.time_step_spec().observation.shape[0]
print(input_size)
output_size = env.time_step_spec().observation.shape[0]
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(input_size, )),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(output_size)
])


optimizer = tf.keras.optimizers.Adam()
loss_history = []

for time_step, action, next_time_step in transitions:
    state_diff = next_time_step.observation - time_step.observation
    
    with tf.GradientTape() as tape:
        print('Observation', time_step.observation)
        print('Action', action)
        pred_state_diff = model(tf.concat([time_step.observation, action], 1), training=True)   
        loss_value = tf.losses.mean_squared_error(state_diff, pred_state_diff)
    
    loss_history.append(loss_value.numpy())
    grads = tape.gradient(loss_value, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
        

print(loss_history)

    

23
Observation tf.Tensor(
[[-0.03723973  0.08865002 -0.03914903 -0.08089941  0.00092869  0.08897705
  -0.09163773  0.04546549  0.01857329  0.09931803 -0.03349365  0.01707685
  -0.04606488 -0.08050357 -0.110457   -0.1112295  -0.12238962]], shape=(1, 17), dtype=float32)
Action tf.Tensor([[ 0.7629349  -0.65688777  0.8418231  -0.6948137   0.36854053 -0.53573465]], shape=(1, 6), dtype=float32)
Observation tf.Tensor(
[[-0.02790391  0.09771752  0.18591745 -0.37610778  0.3022899  -0.20966941
   0.21534038 -0.11377001  0.08316024 -0.03846378  0.12309174  5.5717487
  -6.138163    7.2941446  -7.6280513   7.1246557  -4.271552  ]], shape=(1, 17), dtype=float32)
Action tf.Tensor([[ 0.58457756  0.30973625 -0.9974747   0.7894635   0.7630861  -0.8224938 ]], shape=(1, 6), dtype=float32)
Observation tf.Tensor(
[[-8.3713420e-02  1.3361803e-02  4.0475985e-01 -2.9172997e-03
  -2.0829742e-01 -1.7282575e-02  2.9426774e-01 -4.4427574e-01
   7.2193998e-01 -1.5897454e+00 -2.2498026e+00  4.1471019e+00
   1.132838

In [343]:
from tf_agents.policies import py_policy
from tf_agents.policies import tf_policy
from tf_agents.specs import array_spec
from tf_agents.specs import tensor_spec
from tf_agents.trajectories import policy_step
from tf_agents.trajectories import time_step as ts
from tf_agents.utils import nest_utils


class ModelBasedPolicy(tf_policy.Base):
    
    def __init__(self, 
                 time_step_spec, 
                 action_spec, 
                 dynamics_model_network,
                 num_random_action_selection=4096,
                 horizon=15):
        
        if time_step_spec is None:
            time_step_spec = ts.time_step_spec()
        self._dynamics_model_network = dynamics_model_network
        self._num_random_action_selection=num_random_action_selection
        self._horizon = horizon
        
        super(ModelBasedPolicy, self).__init__(
            time_step_spec=time_step_spec, action_spec=action_spec)
        
    def _action(self, time_step, policy_state, seed):
        
        random_actions = tensor_spec.sample_spec_nest(
            self._action_spec, seed, outer_dims=[self._num_random_action_selection, self._horizon])
        start_state = tf.tile(time_step.observation, [self._num_random_action_selection, 1])
        cost = tf.zeros(shape=[self._num_random_action_selection, 1])
        curr_state = start_state
        for h in range(self._horizon):
            next_state = curr_state + self._dynamics_model_network(tf.concat([curr_state, random_actions[:, h, :]], 1))
            cost += self._cost_fn(curr_state, tf.constant(random_actions[:, h, :]), next_state)
            curr_state = next_state
           
        min_cost_index = tf.math.argmin(cost, axis=1)[0]
        return policy_step.PolicyStep(tf.expand_dims(random_actions[min_cost_index, 0, :], 0), policy_state)
    
    def _cost_fn(self, states, actions, next_states):
        is_tf = tf.is_tensor(states)
        is_single_state = (len(states.get_shape()) == 1) if is_tf else (len(states.shape) == 1)

        if is_single_state:
            states = states[None, ...]
            actions = actions[None, ...]
            next_states = next_states[None, ...]

        scores = tf.zeros(actions.get_shape()[0]) if is_tf else np.zeros(actions.shape[0])

        heading_penalty_factor = 10

        # dont move front shin back so far that you tilt forward
        front_leg = states[:, 6]
        my_range = 0.2
        if is_tf:
            scores += tf.cast(front_leg >= my_range, tf.float32) * heading_penalty_factor
        else:
            scores += (front_leg >= my_range) * heading_penalty_factor

        front_shin = states[:, 7]
        my_range = 0
        if is_tf:
            scores += tf.cast(front_shin >= my_range, tf.float32) * heading_penalty_factor
        else:
            scores += (front_shin >= my_range) * heading_penalty_factor

        front_foot = states[:, 8]
        my_range = 0
        if is_tf:
            scores += tf.cast(front_foot >= my_range, tf.float32) * heading_penalty_factor
        else:
            scores += (front_foot >= my_range) * heading_penalty_factor

        scores -= (next_states[:, 16] - states[:, 16]) / 0.01

        if is_single_state:
            scores = scores[0]

        return scores



In [344]:
from tf_agents.policies import tf_py_policy
from tf_agents.policies import py_tf_policy

my_policy = ModelBasedPolicy(tf_env.time_step_spec(), tf_env.action_spec(), model)
my_policy2 = random_tf_policy.RandomTFPolicy(
                    tf_env.time_step_spec(),
                    tf_env.action_spec())
time_step = tf_env.reset()
action_step = my_policy.action(time_step)
action_step2 = my_policy2.action(time_step)
print(action_step)
print(action_step2)
#tf_env.step(action_step.action)

PolicyStep(action=<tf.Tensor: id=16795473, shape=(1, 6), dtype=float32, numpy=
array([[-0.98933554, -0.43751025, -0.74255943,  0.7513337 , -0.1552701 ,
         0.25850296]], dtype=float32)>, state=(), info=())
PolicyStep(action=<tf.Tensor: id=16795492, shape=(1, 6), dtype=float32, numpy=
array([[ 6.1007166e-01, -4.9070120e-02, -2.3317337e-04, -5.4304695e-01,
        -4.5401669e-01,  6.7937756e-01]], dtype=float32)>, state=(), info=())


In [345]:
from tf_agents.agents import tf_agent
from tf_agents.policies import greedy_policy
from tf_agents.policies import random_py_policy
from tf_agents.policies import random_tf_policy

from tf_agents.replay_buffers import tf_uniform_replay_buffer
from tf_agents.replay_buffers import py_uniform_replay_buffer
from tf_agents.trajectories import trajectory


class ModelBasedAgent(tf_agent.TFAgent):
    
    def __init__(self,
                 time_step_spec,
                 action_spec,
                 dynamics_model_network,
                 optimizer,
                 debug_summaries=False,
                 summarize_grads_and_vars=False,
                 entropy_regularization=None,
                 train_step_counter=None,
                 name=None):
        tf.Module.__init__(self, name=name)
        self._dynamics_model_network = dynamics_model_network  
        
        policy = ModelBasedPolicy(
                    time_step_spec=time_step_spec,
                    action_spec=action_spec,
                    dynamics_model_network=self._dynamics_model_network)
        
        collect_policy = policy

        super(ModelBasedAgent, self).__init__(
            time_step_spec,
            action_spec,
            policy,
            collect_policy,
            train_sequence_length=2,
            debug_summaries=debug_summaries,
            summarize_grads_and_vars=summarize_grads_and_vars,
            train_step_counter=train_step_counter)
        
    def _experience_to_transitions(self, experience):
        transitions = trajectory.to_transition(experience)
        time_steps, policy_steps, next_time_steps = transitions
        actions = policy_steps.action
        
        return time_steps, actions, next_time_steps
                
    def _train(self, experience, weights=None):
        time_steps, actions, next_time_steps = self._experience_to_transitions(experience)
        state_diff = next_time_steps.observation - time_steps.observation
        
        with tf.GradientTape() as tape:
            pred_state_diff = self._dynamics_model_network(tf.concat([time_steps.observation, actions], 2), training=True)   
            loss_value = tf.losses.mean_squared_error(state_diff, pred_state_diff)
            grads = tape.gradient(loss_value, self._dynamics_model_network.trainable_variables)
            optimizer.apply_gradients(zip(grads, self._dynamics_model_network.trainable_variables))
            
        return tf.nest.map_structure(tf.identity, tf_agent.LossInfo(loss_value, ()))


In [346]:
env = suite_mujoco.load('HalfCheetah-v2')
tf_env = tf_py_environment.TFPyEnvironment(env)

input_size = env.action_spec().shape[0] + env.time_step_spec().observation.shape[0]
output_size = env.time_step_spec().observation.shape[0]
dynamics_model_network = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(input_size, )),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(output_size)
])

learning_rate = 1e-3  
optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)

train_step_counter = tf.compat.v2.Variable(0)

agent = ModelBasedAgent(
    tf_env.time_step_spec(),
    tf_env.action_spec(),
    dynamics_model_network=dynamics_model_network,
    optimizer=optimizer,
    train_step_counter=train_step_counter)
agent.initialize()

In [347]:
replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec=agent.collect_data_spec,
    batch_size=tf_env.batch_size,
    max_length=100000)


initial_collect_policy = random_tf_policy.RandomTFPolicy(
                    tf_env.time_step_spec(),
                    tf_env.action_spec())

In [348]:
from tf_agents.metrics import tf_metrics
from tf_agents.drivers import dynamic_episode_driver
from tf_agents.drivers import dynamic_step_driver

num_rollouts = 1
num_episodes = tf_metrics.NumberOfEpisodes()
env_steps = tf_metrics.EnvironmentSteps()

observers = [num_episodes, env_steps, replay_buffer.add_batch]
initial_collect_driver = dynamic_episode_driver.DynamicEpisodeDriver(
    tf_env, initial_collect_policy, observers, num_episodes=num_rollouts)
onpolicy_collect_driver = dynamic_episode_driver.DynamicEpisodeDriver(
    tf_env, agent.collect_policy, observers, num_episodes=1)

#print('final_time_step', final_time_step)
#print('Number of Steps: ', env_steps.result().numpy())


In [349]:
time_step = None
policy_state = initial_collect_policy.get_initial_state(tf_env.batch_size)

initial_collect_driver.run()
dataset = replay_buffer.as_dataset(
    sample_batch_size=64,
    num_steps=2)

iterator = iter(dataset)

model_iterations = 1
policy_iterations = 1

for _ in range(model_iterations):
    print('Hello')
    experience, _ = next(iterator)
    loss_info = agent.train(experience)
    
print('Number of Episodes: ', num_episodes.result().numpy()) 
for _ in range(policy_iterations):
    onpolicy_collect_driver.run()
    experience, _ = next(iterator)
    loss_info = agent.train(experience)
   

print('Done training')
    

Hello
Number of Episodes:  1
Done training


In [350]:
def embed_mp4(filename):
    video = open(filename, 'rb').read()
    b64 = base64.b64encode(video);
    tag = '''
    <video width="640" height="480" controls>
    <source src="data:video/mp4;base64,{0}" type="video/mp4">
    Your browser does not support the video tag.
    </video>'''.format(b64.decode())

    return IPython.display.HTML(tag)

In [ ]:
num_episodes = 3
video_filename = 'imageio.mp4'
with imageio.get_writer(video_filename, fps=60) as video:
    for _ in range(num_episodes):
        time_step = tf_env.reset()
        video.append_data(env.render())
        while not time_step.is_last():
            action_step = agent.policy.action(time_step)
            time_step = tf_env.step(action_step.action)
            video.append_data(env.render())
        
embed_mp4(video_filename)

W0523 17:00:06.227456 140425894250240 _io.py:361] IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (500, 500) to (512, 512) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
